In [2]:
# Import necessary libraries
from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame
import pandas as pd
from dotenv import load_dotenv
import os

# Set your Alpaca API credentials
API_KEY = os.environ.get('ALPACA_API_KEY')
SECRET_KEY = os.environ.get('ALPACA_API_SECRET')

# Initialize the Alpaca client
client = StockHistoricalDataClient(API_KEY, SECRET_KEY)

# Define the request parameters
request_params = StockBarsRequest(
    symbol_or_symbols=['AAPL'],
    timeframe=TimeFrame.Day,
    start='2022-01-01',
    end='2022-12-31'
)

# Fetch the historical data
bars = client.get_stock_bars(request_params)

# Convert the data to a pandas DataFrame
df = bars.df

# Display the DataFrame
df.head()

                                    open    high     low   close       volume  \
symbol timestamp
AAPL   2022-01-03 05:00:00+00:00  177.83  182.88  177.71  182.01  112486091.0
       2022-01-04 05:00:00+00:00  182.64  182.94  179.12  179.70  106090378.0
       2022-01-05 05:00:00+00:00  179.61  180.17  174.64  174.92   95142198.0
       2022-01-06 05:00:00+00:00  172.70  175.30  171.64  172.00  103899632.0
       2022-01-07 05:00:00+00:00  172.89  174.14  171.03  172.17   94554334.0

                                  trade_count        vwap
symbol timestamp
AAPL   2022-01-03 05:00:00+00:00     772699.0  181.395005
       2022-01-04 05:00:00+00:00     831898.0  180.596889
       2022-01-05 05:00:00+00:00     848518.0  177.382297
       2022-01-06 05:00:00+00:00     960344.0  173.031383
       2022-01-07 05:00:00+00:00     715419.0  172.441994

In [1]:
from dotenv import load_dotenv
load_dotenv()
import os
os.environ.get("ALPACA_API_KEY")

'PKQI7C6PUZIL0JK5DZ8U'